name: "Code Scanning"

on:
  push:
    branches: [main]
  schedule:
    - cron: "0 0 * * *"

jobs:
  scanning:
    runs-on: ubuntu-latest
    name: Run CodeQL & Snyk scanning
    permissions:
      actions: read
      contents: read
      security-events: write

    steps:
      - uses: actions/checkout@v2
      - name: Pull submodules
        run: git submodule update --recursive --init
      - name: Build a Docker image
        run: docker build -t blackcat:snyk .
      - name: Run Snyk (Docker)
        continue-on-error: true
        uses: snyk/actions/docker@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          image: blackcat:snyk
          args: --file=Dockerfile
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2
        with:
          languages: "javascript"
      - name: Setup node environment
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Run build
        run: yarn install
      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v2
      - name: Run Snyk (Node.js)
        uses: snyk/actions/node@master
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --sarif-file-output=node.sarif
      - name: Upload result to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: snyk.sarif
      - name: Upload result to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: node.sarif
